apiVersion: v1
kind: Service
metadata:
  labels:
    app: resumebuilder
    env: dev
  name: resumebuilder
  namespace: dev-apps
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
  selector:
    app: resumebuilder
  type: NodePort
